# Generated by Django 5.1.2 on 2025-03-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySourceReplica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercache',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
