# Generated by Django 5.1.2 on 2025-03-30 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySourceReplica', '0002_weathercache_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('vibe', models.CharField(max_length=100)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='MySourceReplica.city')),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherCache',
        ),
    ]
