# Generated by Django 5.1.2 on 2025-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySourceReplica', '0003_weathersnapshot_delete_weathercache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathersnapshot',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='weathersnapshot',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weathersnapshot',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
